### ISSUE TITLE
Missing format string in attack_take_screenshot.py

### ISSUE THREAD

**Issue by 1ncludeSteven** [fkie-cad/socbed#83]
**Describe the bug**
When running fkie-cad/socbed/src/attacks/attack_take_screenshot.py, a bug will occur because of missing format string in following lines:

```python
def _collect_files(self):
        file = self.screenshot_file
        # !!!!!! we should use f"screenshot -p {file}" rather than "screenshot -p {file}"
        self.ssh_client.write_lines(self.handler.stdin, ["screenshot -p {file}",
                                                         "background"])
```

**To Reproduce**
use attackconsole, run c2_take_screenshot after running infect_email_exe

**Expected behavior**
![image](https://github.com/user-attachments/assets/ee9779b4-eb27-4d90-83be-aa729293a400)

**Current behavior**
A screenshot should be store in /root/screenshot.jpeg rather then saved in /root/{file}
![image](https://github.com/user-attachments/assets/dc765684-fe75-4ce6-9963-c7737f34fa41)

**Comment by Maspital** [comment]
Thanks for the heads up :) my first thought was "why wasn't that caught by some unit tests" - turned out there are none for this specific attack.
