### ISSUE TITLE
Clone Client with the same VRDE port

### ISSUE THREAD

**Issue by 1ncludeSteven** [fkie-cad/socbed#86]
**Describe the bug**
When we use `vmcontrol/sessionhandler/sessionhandler.py#CloneCreator` to create ClinetClone from Clinet, those Cloned-Clinets are share the same VRDE port.
**To Reproduce**
use `vboxmanage showvminfo ClientClone1`, `vboxmanage showvminfo ClientClone2`, `vboxmanage showvminfo ClientClone3`, we can found all these three cloned clients share the same vrde port so that we can only access ClientClone1 using `rdesktop -g 1024x768 127.0.0.1:{vrde_port}`

**Expected behavior**
When clone client, we should also set the vrde port so that cloned client share different ports

**Screenshots**
the result of `vboxmanage showvminfo ClientClone1`
![image](https://github.com/user-attachments/assets/f63079a8-c3c4-43da-b6c7-e3bb5dd0892d)

**Comment by Maspital** [comment]
Hi, you're absolutely right. I think we never noticed this since we never actually needed to access our machines via VRDE, we always did so locally.

Modified to session setup to assign a unique VRDE port to each clone, starting at 6000, then 6001, etc...
