### ISSUE TITLE
Missing Installation Step in Readme.md

### ISSUE THREAD

**Issue by darshjain** [fkie-cad/socbed#87]
I was installing SOCBED on a fresh system and there is a command missing for installation of ansible to smoothen the process, it.

**Comment by Maspital** [comment]
Could you elaborate on the step that is missing? I just installed SOCBED an a fresh system and it worked fine using the instructions as written. One problem that can happen is different versions of `ansible-core` clashing, but that a) shouldn't happen on a fresh system and b) should also be prevented by the venv.

**Comment by Maspital** [comment]
Closing due to missing info, feel free to re-open when needed.
