### ISSUE TITLE
Missing dependencies in Attacker Server 

### ISSUE THREAD

**Issue by 1ncludeSteven** [fkie-cad/socbed#93]
**Describe the bug**
Missing two dependencies in Attack Search:
* missing pip dependencies of aiosmptd when updating tests after switching from smptd to aiosmtpd in Attacker
* missing systemd-resolved apt in Attacker Server so that the `/run/systemd/resolv/resolv.conf` is not exist

**To Reproduce**
For the first missing dependency:  running `/usr/bin/python3 /usr/bin/external_mail_handler.py`, then the failure is as below:
![image](https://github.com/user-attachments/assets/4fa6bd99-cc43-4be0-b955-d69e6286528f)
And after install python3-aiosmtpd, we can running `/usr/bin/python3 /usr/bin/external_mail_handler.py` successfully, however, the service still can not running successfully with error as below:
![image](https://github.com/user-attachments/assets/120b0259-3198-42e8-a790-0e98967b15c7)

For the second: running `ls /run/systemd/`, the result doesn't have a directory named `resolv`

**Expected behavior**
* install python3-aiosmtpd in Attacker using apt, and change the `input('SMTP server running. Press Return to stop server and exit.')` to below code:
```python
    try:
        while True:
            pass  # keep running
    except KeyboardInterrupt:
        self.controller.stop()
```
* install systemd-resolved after attacker is installed using apt

**Comment by Maspital** [comment]
Yup, missed that when switching from the deprecated `smtpd` module.
